
package view;

/**
 *
 * @author YU7
 */
public class FrmTutorial extends javax.swing.JFrame {

    /**
     * Creates new form FrmTutorial
     */
    public FrmTutorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tutorial JTruco v1.0");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("TRUCO Paulista v1.0\n\n1 - A distribuição das cartas é feita de forma automática e aleatória pelo nosso sistema, não ha intervenção de nenhum jogador.\n\n2 - Número de cartas: 40 (retirando-se, 8, 9, 10 e Curingas)\n3 - Distribuição: 3 cartas para cada participante\n4 - Objetivo: Quem fizer 12 pontos, ganha a partida.\n\n5 - Sequência da maior para a menor: 3 2 A K J Q 7 6 5 4 (não importando os naipes).\n\n6 - A manilha é nova ou variável, sendo determinada pela vira, a carta ao lado! sendo uma carta acima dela será a mais forte da mão!\n\n7 - Dentre as manilhas, a ordem de “força” obedece o naipe, da seguinte maneira (do maior para o menor):\nPaus > Copas > Espadas > Ouros\n\n8 - Não há empates nas manilhas, porém há empates nas determinadas jogadas sendo qualquer outra carta!\n\n9  - Caso empate a 1ª mão, quem ganha a 2ª mão leva\n10 - Caso empate a 1ª mão e a 2ª mão, quem ganha a ultima leva\n11 - Caso empate a 1ª mão, 2ª mão e a 3ª mão a rodada ninguem ganha ponto!\n\nDesenvolvido por: @YU7\nContato: alexandrehenrique.esy.es\nemai: alexhcb.7392@gmail.com\nSkype : alexandre.yusuke");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
